#==========================  Modules configuration =============================
auditbeat.modules:

- module: auditd
  socket_type: multicast
  resolve_ids: true
  failure_mode: log
  backlog_limit: 16384
  rate_limit: 0
  include_raw_message: false
  include_warnings: false
  backpressure_strategy: auto
  # audit_rule_files: [ '${path.config}/audit.rules.d/*.conf' ]
  # no rules specified, auditd will run and manage rules
  # see https://www.elastic.co/guide/en/beats/auditbeat/master/auditbeat-module-auditd.html

  # don't forward some things that are always going to be happening
  # (/proc/ accesses by beats and browser for the kiosk) to cut down on noise
  # and some other approved common stuff that would clutter the logs
  processors:
  - drop_event:
      when:
        or:
          - and:
              - equals:
                  auditd.data.syscall: 'setsockopt'
              - equals:
                  auditd.summary.object.type: 'network-device'
              - or:
                  - equals:
                      auditd.summary.how: '/usr/sbin/tcpdump'
                  - equals:
                      auditd.summary.how: '/opt/zeek/bin/zeek'
                  - equals:
                      auditd.summary.how: '/usr/sbin/netsniff-ng'
                  - equals:
                      auditd.summary.how: '/opt/moloch/bin/moloch-capture'
          - and:
              - equals:
                  auditd.message_type: 'syscall'
              - equals:
                  auditd.summary.object.type: 'file'
              - or:
                - and:
                    - or:
                        - equals:
                            auditd.data.syscall: 'open'
                        - equals:
                            auditd.data.syscall: 'openat'
                    - regexp:
                        auditd.summary.object.primary: '^/(proc/|etc/localtime|usr/lib/x86_64-linux-gnu/gconv/gconv-modules\.cache)'
                    - or:
                        - equals:
                            auditd.summary.how: '/usr/share/auditbeat/bin/auditbeat'
                        - equals:
                            auditd.summary.how: '/usr/share/metricbeat/bin/metricbeat'
                        - equals:
                            auditd.summary.how: '/opt/firefox/firefox-bin'
                        - equals:
                            auditd.summary.how: '/opt/firefox/firefox'
                        - equals:
                            auditd.summary.how: '/usr/sbin/tcpdump'
                        - equals:
                            auditd.summary.how: '/opt/zeek/bin/zeek'
                        - equals:
                            auditd.summary.how: '/usr/sbin/netsniff-ng'
                        - equals:
                            auditd.summary.how: '/opt/moloch/bin/moloch-capture'
                - and:
                    - or:
                        - equals:
                            auditd.data.syscall: 'open'
                        - equals:
                            auditd.data.syscall: 'openat'
                    - not:
                        has_fields: ['auditd.summary.object.primary']
                    - or:
                      - equals:
                          auditd.summary.how: 'supervisorctl'
                      - equals:
                          auditd.summary.how: '/usr/share/metricbeat/bin/metricbeat'
                - and:
                    - equals:
                        auditd.data.syscall: 'open'
                    - regexp:
                        auditd.summary.object.primary: '^/dev/'
                    - equals:
                        auditd.summary.how: '/usr/sbin/hddtemp'
                - and:
                    - equals:
                        auditd.data.syscall: 'open'
                    - regexp:
                        auditd.summary.object.primary: '^/.+/__pycache__/$'
                    - regexp:
                        auditd.summary.how: '^python3'
                - and:
                    - or:
                      - equals:
                          auditd.summary.how: 'bash'
                      - equals:
                          auditd.summary.how: '/bin/bash'
                    - equals:
                        auditd.summary.actor.primary: 'sensor'
                    - equals:
                        auditd.data.syscall: 'chown'
                    - equals:
                        auditd.summary.object.primary: '/home/sensor/.bash_history'
                - and:
                    - equals:
                        auditd.summary.how: '/opt/firefox/firefox-bin'
                    - equals:
                        auditd.summary.actor.primary: 'sensor'
                    - or:
                        - equals:
                            auditd.data.syscall: 'chmod'
                        - equals:
                            auditd.data.syscall: 'open'
                        - equals:
                            auditd.data.syscall: 'openat'
                        - equals:
                            auditd.data.syscall: 'rename'
                        - equals:
                            auditd.data.syscall: 'renameat'
                        - equals:
                            auditd.data.syscall: 'rmdir'
                        - equals:
                            auditd.data.syscall: 'unlink'
                    - or:
                        - regexp:
                            auditd.summary.object.primary: '^/home/sensor/\.(cache/)?mozilla/firefox/'
                        - regexp:
                            auditd.summary.object.primary: '^/home/sensor/\.config/mimeapps\.'
                        - regexp:
                            auditd.summary.object.primary: '^/tmp/(Temp-|firefox)'
                        - equals:
                            auditd.summary.object.primary: '/opt/firefox/fonts/'
                - and:
                    - or:
                        - equals:
                            auditd.data.syscall: 'open'
                        - equals:
                            auditd.data.syscall: 'openat'
                        - equals:
                            auditd.data.syscall: 'unlink'
                        - equals:
                            auditd.data.syscall: 'rename'
                        - equals:
                            auditd.data.syscall: 'renameat'
                    - regexp:
                        auditd.summary.object.primary: '^/(capture/|usr/lib/python)'
                    - or:
                        - equals:
                            auditd.summary.how: 'zeekctl'
                        - equals:
                            auditd.summary.how: 'supervisorctl'
                - and:
                    - equals:
                        auditd.summary.object.primary: '/opt/sensor/sensor_ctl/filebeat/data/registry/filebeat/data.json'
                    - equals:
                        auditd.summary.how: '/usr/share/filebeat/bin/filebeat'
                # I don't like filtering this, but see https://github.com/zeek/zeek/issues/259#issuecomment-564735946
                # zeekctl is doing this, but there's nothing to indicate that's what it is.
                # For now I've tried to narrow it as much as possible, because it's *so* much noise
                - and:
                    - or:
                        - equals:
                            auditd.data.syscall: 'unlink'
                        - equals:
                            auditd.data.syscall: 'openat'
                    - equals:
                        auditd.result: 'fail'
                    - equals:
                        auditd.summary.how: 'python'
                    - regexp:
                        auditd.summary.object.primary: '^/usr/lib/python'


- module: file_integrity
  paths:
  - /bin
  - /opt/zeek
  - /sbin
  - /usr/bin
  - /usr/local/bin
  - /usr/sbin

# system module is experimental: https://www.elastic.co/blog/introducing-auditbeat-system-module
# ALSO system module is ONLY available with non-OSS license

# - module: system
#   datasets:
#     - host # General host information, e.g. uptime, IPs
#     - user # User information
#   period: 1m
#   user.detect_password_changes: true

# - module: system
#   datasets:
#     - process # Started and stopped processes
#     - socket  # Opened and closed sockets
#   period: 1s

#   # drop noise
#   processors:
#   - drop_event:
#       when:
#         or:
#           - and:
#               - equals:
#                   event.module: 'system'
#               - equals:
#                   event.dataset: 'socket'
#               - equals:
#                   destination.ip: '127.0.0.1'
#               - equals:
#                   source.ip: '127.0.0.1'
#           - and:
#               - equals:
#                   event.module: 'system'
#               - equals:
#                   event.dataset: 'socket'
#               - equals:
#                   destination.ip: "${BEAT_ES_HOST}"
#               - equals:
#                   destination.port: "${BEAT_ES_PORT}"
#           - and:
#               - equals:
#                   event.module: 'system'
#               - equals:
#                   event.dataset: 'socket'
#               - equals:
#                   destination.ip: "${BEAT_KIBANA_HOST}"
#               - equals:
#                   destination.port: "${BEAT_KIBANA_PORT}"
#           - and:
#               - equals:
#                   event.module: 'system'
#               - equals:
#                   event.dataset: 'process'
#               - or:
#                   - equals:
#                       process.executable: '/bin/sleep'
#                   - equals:
#                       process.executable: '/usr/bin/sort'
#                   - equals:
#                       process.executable: '/usr/bin/tail'
#                   - equals:
#                       process.executable: '/usr/bin/clear'
#                   - equals:
#                       process.executable: '/usr/bin/head'
#                   - equals:
#                       process.executable: '/bin/date'
#                   - equals:
#                       process.executable: '/bin/ls'
#                   - equals:
#                       process.executable: '/usr/bin/stat'
#                   - equals:
#                       process.executable: '/usr/bin/cut'
#                   - equals:
#                       process.executable: '/usr/bin/xargs'
#                   - equals:
#                       process.executable: '/usr/bin/tr'
#                   - equals:
#                       process.executable: '/bin/grep'
#                   - equals:
#                       process.executable: '/bin/sed'
#                   - equals:
#                       process.executable: '/bin/df'
#                   - equals:
#                       process.executable: '/usr/bin/du'
#                   - equals:
#                       process.executable: '/usr/bin/gawk'
#                   - and:
#                       - equals:
#                           process.executable: '/bin/bash'
#                       - contains:
#                           process.args: '/usr/local/bin/prune_files.sh'
#                   - and:
#                       - equals:
#                           process.executable: '/usr/bin/find'
#                       - contains:
#                           process.args: '-xdev'
#                       - contains:
#                           process.args: '-mindepth'
#                       - contains:
#                           process.args: '-maxdepth'
#                       - contains:
#                           process.args: '-printf'

#================================ General ======================================
fields_under_root: true

#================================ Outputs ======================================

#-------------------------- Elasticsearch output -------------------------------
output.elasticsearch:
  enabled: true
  hosts: ["${BEAT_ES_HOST}:${BEAT_ES_PORT}"]
  protocol: "${BEAT_ES_PROTOCOL}"
  username: "${BEAT_HTTP_USERNAME}"
  password: "${BEAT_HTTP_PASSWORD}"
  ssl.verification_mode: "${BEAT_ES_SSL_VERIFY}"

setup.template.enabled: true
setup.template.overwrite: false
setup.template.settings:
  index.number_of_shards: 1
  index.number_of_replicas: 0

#============================== Dashboards =====================================
setup.dashboards.enabled: "${BEAT_KIBANA_DASHBOARDS_ENABLED}"
setup.dashboards.directory: "${BEAT_KIBANA_DASHBOARDS_PATH}"

#============================== Kibana =====================================
setup.kibana:
  host: "${BEAT_KIBANA_HOST}:${BEAT_KIBANA_PORT}"
  protocol: "${BEAT_KIBANA_PROTOCOL}"
  username: "${BEAT_HTTP_USERNAME}"
  password: "${BEAT_HTTP_PASSWORD}"
  ssl.verification_mode: "${BEAT_KIBANA_SSL_VERIFY}"

#================================ Logging ======================================
logging.metrics.enabled: false

